# coding=utf-8

# sync mode
MASTER_PREDICT = True
REPLICA_BUFFER = False
REPLICA_INTERPOLATION = False
REPLICA_EXTRAPOLATION = False

# control mod
CONTROL_WASD = 'WASD'
CONTROL_MOUSE = 'Mouse Follow'
CONTROL_LINE = 'Mouse Line'
CONTROL_MODE_LIST = [CONTROL_WASD, CONTROL_MOUSE, CONTROL_LINE]
CONTROL_MODE = CONTROL_WASD
