# coding=utf-8

# ControlMod
CONTROL_WASD = 'WASD'
CONTROL_MOUSE = 'Mouse Follow'
CONTROL_LINE = 'Mouse Line'
CONTROL_MODE_LIST = [CONTROL_WASD, CONTROL_MOUSE, CONTROL_LINE]
CONTROL_MODE = CONTROL_WASD

# SyncMode
MASTER_PREDICT = True
REPLICA_BUFFER = False
REPLICA_INTERPOLATION = False
REPLICA_EXTRAPOLATION = False

# Network
NETWORK_CMD_FRAME = 30
NETWORK_CLIENT_BUFFER = 0
NETWORK_SNAPSHOT_FRAME = 30
NETWORK_SERVER_BUFFER = 0

# Physics
PHYSICS_BLEND_FRAME = 60
